import { Link } from 'react-router'
import { PageTitle } from '../components/UI'

export default function Privacy() {
  return <article className="max-w-3xl space-y-8 rounded-3xl bg-surface p-6 text-sm leading-7 text-ink/80 ring-1 ring-line sm:p-10">
    <PageTitle title="Privacy" />
    <header><h1 className="font-display text-4xl font-extrabold tracking-tight">Privacy policy</h1><p className="mt-2 text-muted">Effective October 3, 2026</p><p className="mt-4">TerpsDining is an independent dining information app maintained by the developer of <a className="text-brand underline" href="https://github.com/sbharga/terpsdining" target="_blank" rel="noopener noreferrer">sbharga/terpsdining</a>. It is not affiliated with the University of Maryland. This policy explains how the app handles your information.</p></header>
    <section><h2 className="font-display text-lg font-bold text-ink">Information we collect</h2><ul className="mt-2 list-disc space-y-2 pl-5"><li>You can browse menus, hours, nutrition, and serving history without signing in.</li><li>If you sign in with Google, Supabase receives your Google account identifier, email address, and basic profile information such as your name and profile picture. TerpsDining does not receive your Google password or request access to Gmail, Drive, Calendar, or Contacts.</li><li>When you rate an item, we store your account identifier, the item identifier, your 1–5 star rating, and creation and update timestamps. There are no text reviews.</li><li>Hosting and authentication providers may process technical request information, such as IP addresses, browser information, and timestamps, to operate and secure the service.</li></ul></section>
    <section><h2 className="font-display text-lg font-bold text-ink">How information is used</h2><p className="mt-2">Account information is used to authenticate you and associate your ratings with your account so you can edit or remove them. Ratings are used to calculate item averages and rankings. Technical information supports service operation, troubleshooting, and security. Google account information is not used for advertising or sold.</p></section>
    <section><h2 className="font-display text-lg font-bold text-ink">What others can see</h2><p className="mt-2">Item rating averages and rating counts are public. The app does not publicly display your individual ratings, email address, or Google profile. Authorized maintainers can access stored data to administer the service. An aggregate based on very few ratings may reveal the value of an individual rating, but the app does not attach your identity to it.</p></section>
    <section><h2 className="font-display text-lg font-bold text-ink">Service providers</h2><p className="mt-2">Google provides sign-in, Supabase stores account and rating data and provides authentication and image storage, and Vercel hosts the website. These providers process information under their own policies and may process it outside your country.</p><ul className="mt-2 list-disc pl-5"><li><a className="text-brand underline" href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google privacy policy</a></li><li><a className="text-brand underline" href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer">Supabase privacy policy</a></li><li><a className="text-brand underline" href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">Vercel privacy policy</a></li></ul></section>
    <section><h2 className="font-display text-lg font-bold text-ink">Browser storage</h2><p className="mt-2">Supabase uses browser local storage to keep your authentication session between visits. Signing out clears the app’s stored authentication session. Clearing browser storage does not delete your account or ratings. The app does not include advertising trackers or a third-party analytics integration. Google and service providers may use their own cookies when you interact with their services.</p></section>
    <section><h2 className="font-display text-lg font-bold text-ink">Retention and your choices</h2><p className="mt-2">Accounts and ratings are retained until removed or the service is discontinued; the app does not currently apply automatic expiration. You can remove a rating by clicking the same selected star again. To request access, correction, or deletion of your account and associated ratings, email <a className="text-brand underline" href="mailto:support@docet.org">support@docet.org</a> from the address used to sign in. We may need to verify your identity before acting. Do not send passwords or authentication tokens.</p><p className="mt-2">You can also revoke Google access in your Google Account settings. Revoking access or signing out does not itself delete data already stored in Supabase. Provider backups and operational logs may remain subject to the provider’s retention procedures after live account data is removed.</p></section>
    <section><h2 className="font-display text-lg font-bold text-ink">Security and children</h2><p className="mt-2">The app uses Supabase authentication and database access controls to restrict individual rating access. No service can guarantee absolute security. TerpsDining is not directed at children under 13; if you believe a child has provided personal information, contact us to request removal.</p></section>
    <section><h2 className="font-display text-lg font-bold text-ink">Changes and contact</h2><p className="mt-2">Policy changes will be posted on this page with an updated effective date. For privacy questions, contact <a className="text-brand underline" href="mailto:support@docet.org">support@docet.org</a>. See also our <Link className="text-brand underline" to="/terms">terms of use</Link>.</p></section>
  </article>
}
