import { Link } from 'react-router'
import { PageTitle } from '../components/UI'

export default function Terms() {
  return <article className="max-w-3xl space-y-8 rounded-3xl bg-surface p-6 text-sm leading-7 text-ink/80 ring-1 ring-line sm:p-10">
    <PageTitle title="Terms" />
    <header><h1 className="font-display text-4xl font-extrabold tracking-tight">Terms of use</h1><p className="mt-2 text-muted">Effective October 3, 2026</p><p className="mt-4">These terms apply to your use of TerpsDining. By using the website, you agree to these terms. If you do not agree, do not use the service.</p></header>
    <section><h2 className="font-display text-lg font-bold text-ink">Independent information service</h2><p className="mt-2">TerpsDining is an independent project, not an official University of Maryland service and not affiliated with or endorsed by UMD. It organizes dining hours, menus, nutrition information, serving history, and user ratings. Information can change, be delayed, or be incomplete. A listed item or serving history does not guarantee that an item is currently available.</p></section>
    <section><h2 className="font-display text-lg font-bold text-ink">Food safety and accuracy</h2><p className="mt-2">Do not rely on TerpsDining to decide whether food is safe for an allergy, intolerance, medical condition, or dietary requirement. Allergen and dietary filters are informational, do not establish the absence of an ingredient, and do not account for cross-contact. Nutrition and ingredient information may vary by portion and preparation. Confirm information with UMD Dining staff and official labels before eating. The website does not provide medical or nutrition advice.</p><p className="mt-2">Food images are illustrative and may not depict the actual dining hall item. User ratings reflect opinions, not food safety or nutritional quality.</p></section>
    <section><h2 className="font-display text-lg font-bold text-ink">Accounts and ratings</h2><p className="mt-2">Browsing does not require an account. Google sign-in is required to submit ratings. Keep your Google account secure and do not use another person’s account without permission. You may submit one editable 1–5 star rating per item and remove it by clicking the selected star again. Text comments are not supported. You must be at least 13 to create an account and satisfy any higher minimum age required by applicable law or your Google account.</p></section>
    <section><h2 className="font-display text-lg font-bold text-ink">Acceptable use</h2><p className="mt-2">Do not manipulate ratings using multiple accounts or automation, impersonate others, attempt unauthorized access, circumvent security controls, or disrupt the service. We may remove abusive ratings or restrict access to protect users and service integrity.</p></section>
    <section><h2 className="font-display text-lg font-bold text-ink">Third-party content and services</h2><p className="mt-2">Dining information comes from UMD Dining sources. Images and other third-party content remain subject to their owners’ rights. Google, Supabase, Vercel, and linked websites operate under their own terms and policies. Linking to a source does not imply endorsement. These terms do not grant ownership of third-party content.</p></section>
    <section><h2 className="font-display text-lg font-bold text-ink">Availability and responsibility</h2><p className="mt-2">The service is provided “as is” and “as available.” To the extent permitted by applicable law, we do not warrant its accuracy, completeness, availability, or suitability for a particular purpose, and are not liable for indirect or consequential losses arising from its use. Nothing in these terms excludes liability or consumer rights that cannot lawfully be excluded. The service or its features may change or be discontinued.</p></section>
    <section><h2 className="font-display text-lg font-bold text-ink">Privacy and account deletion</h2><p className="mt-2">Our <Link className="text-brand underline" to="/privacy">privacy policy</Link> explains account information, rating storage, service providers, and deletion requests. Signing out or revoking Google access does not itself delete your stored account or ratings.</p></section>
    <section><h2 className="font-display text-lg font-bold text-ink">Changes and contact</h2><p className="mt-2">Updated terms will be posted here with a revised effective date. For questions, account requests, or concerns about content, email <a className="text-brand underline" href="mailto:support@docet.org">support@docet.org</a>. Do not include passwords or authentication tokens.</p></section>
  </article>
}
